apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x3gh5ro9w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x3gh5ro9w-python 
  name: x3gh5ro9w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x3gh5ro9w-python 
